gighub5/Models/Gig.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace gighub5.Models
{
    public class Gig
    {
        public int id { get; set; }
        
        public ApplicationUser Artist { get; set; }
        [Required]
        public String ArtistId { get; set; }
        public DateTime DateTime { get; set; }
        [Required]
        [StringLength(255)]
        public String Venue { get; set; }
        
        public Genre Genre { get; set; }
        [Required]
        public Byte GenreId { get; set; }


    }
}

gighub5/Controllers/GigsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using gighub5.Models;
using gighub5.ViewModels;
using Microsoft.AspNet.Identity;

namespace gighub5.Controllers
{
    public class GigsController : Controller
    {
        // GET: Gigs
        private readonly ApplicationDbContext _context;
        public GigsController()
        {
            _context = new ApplicationDbContext();
        }
        [Authorize]
        
        public ActionResult Create()
        {
            var viewModel = new GigFormViewModel 
            { 
                Genres = _context.Genres.ToList()
            };


            return View(viewModel);
        }
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(GigFormViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                viewModel.Genres = _context.Genres.ToList();
                return View("Create", viewModel);
            }
            var gig = new Gig
            { ArtistId= User.Identity.GetUserId(),
            DateTime =viewModel.GetDateTime(), 
            GenreId=viewModel.Genre,
            Venue=viewModel.Venue
            
            };
            _context.Gigs.Add(gig);
            _context.SaveChanges();
            return RedirectToAction("Index", "Home");

        }
    }
}

gighub5/Views/Gigs/Create.cshtml
@model gighub5.ViewModels.GigFormViewModel

    @{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Add a Gig</h2>
@using (Html.BeginForm("Create","Gigs"))
{@Html.AntiForgeryToken()
<div class="form-group">
        @Html.LabelFor(m => m.Venue)
        @Html.TextBoxFor(m => m.Venue, new  {@class ="form-control" })
        @Html.ValidationMessageFor(m=>m.Venue)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Date)
        @Html.TextBoxFor(m => m.Date, new { @class = "form-control" })
        @Html.ValidationMessageFor(m=>m.Date)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Time)
        @Html.TextBoxFor(m => m.Time , new { @class = "form-control" })
        @Html.ValidationMessageFor(m=>m.Time)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Genre)
        @Html.DropDownListFor(m =>m.Genre, new SelectList(Model.Genres,"Id","Name"),"",new { @class="form-control"})
        @Html.ValidationMessageFor(m=>m.Genre)
    </div>
    <button type="submit"  class="btn btn-primary">Save</button>
    <div class="form-group"></div>
    <div class="form-group"></div>
}
@section scripts{
 @Scripts.Render("~/bundles/jqueryval")
}